name: Build and Release Portfolio Manager

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            extension: .exe
            icon: icon.ico
          - os: macos-latest
            platform: darwin
            extension: ""
            icon: icon.png
          - os: ubuntu-latest
            platform: linux
            extension: ""
            icon: icon.png

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libgtk-3-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libasound2-dev \
          libglib2.0-dev \
          libffi-dev \
          shared-mime-info

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Flet import
      run: |
        python -c "import flet; print('Flet import successful')"
        
    - name: Debug environment
      run: |
        echo "Python version: $(python --version)"
        echo "Platform: ${{ matrix.platform }}"
        echo "OS: ${{ matrix.os }}"
        pip list | grep -E "(flet|pyinstaller)"
        
    - name: Build executable using build.py
      run: |
        echo "Building using build.py script..."
        python build.py
      continue-on-error: true
      
    - name: Alternative build attempt if first failed
      if: failure()
      shell: bash
      run: |
        echo "First build failed, trying simple PyInstaller approach..."
        python -m PyInstaller --onefile --name "PortfolioManager-${{ matrix.platform }}" main_flet.py
        
    - name: Check build output
      shell: bash
      run: |
        echo "=== Build directory contents ==="
        if [ -d "dist" ]; then
          ls -la dist/
        else
          echo "No dist directory"
        fi
        echo "=== All files in dist ==="
        if [ -d "dist" ]; then
          find dist/ -type f -name "*"
        else
          echo "No files found"
        fi

    - name: Copy and rename artifact if needed
      shell: bash
      run: |
        echo "Looking for built artifacts..."
        if [ -d "dist" ]; then
          # Find the first built executable
          built_file=$(find dist/ -name "PortfolioManager*" -type f | head -1)
          expected_name="dist/PortfolioManager-${{ matrix.platform }}${{ matrix.extension }}"
          
          if [ -n "$built_file" ] && [ "$built_file" != "$expected_name" ]; then
            echo "Found: $built_file"
            echo "Expected: $expected_name"
            cp "$built_file" "$expected_name"
            echo "Copied $built_file to $expected_name"
          elif [ -n "$built_file" ]; then
            echo "File already has correct name: $built_file"
          else
            echo "No built files found"
          fi
          
          echo "Final artifact check:"
          ls -la dist/
        else
          echo "No dist directory found"
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PortfolioManager-${{ matrix.platform }}
        path: |
          dist/PortfolioManager-${{ matrix.platform }}${{ matrix.extension }}
          dist/PortfolioManager-linux${{ matrix.extension }}
          dist/PortfolioManager-darwin${{ matrix.extension }}
          dist/PortfolioManager-windows${{ matrix.extension }}
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
      continue-on-error: true

    - name: Display artifact structure
      run: |
        echo "=== Artifact Directory Structure ==="
        find artifacts/ -type f -exec ls -la {} \; || echo "No artifacts found"
        echo "=== End Structure ==="

    - name: Prepare release files
      run: |
        mkdir -p release-files
        
        # Copy available artifacts to release-files directory
        if [ -f "artifacts/PortfolioManager-windows/PortfolioManager-windows.exe" ]; then
          cp "artifacts/PortfolioManager-windows/PortfolioManager-windows.exe" "release-files/"
          echo "✅ Windows executable found"
        else
          echo "❌ Windows executable not found"
        fi
        
        if [ -f "artifacts/PortfolioManager-darwin/PortfolioManager-darwin" ]; then
          cp "artifacts/PortfolioManager-darwin/PortfolioManager-darwin" "release-files/"
          echo "✅ macOS executable found"
        else
          echo "❌ macOS executable not found"
        fi
        
        if [ -f "artifacts/PortfolioManager-linux/PortfolioManager-linux" ]; then
          cp "artifacts/PortfolioManager-linux/PortfolioManager-linux" "release-files/"
          echo "✅ Linux executable found"
        else
          echo "❌ Linux executable not found"
        fi
        
        ls -la release-files/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: release-files/*
        name: Portfolio Document Manager ${{ github.ref_name }}
        body: |
          ## 🎉 Portfolio Document Manager ${{ github.ref_name }}

          ### ✨ Major Updates - Modern Flet UI

          Complete transition from Tkinter to **Flet** for a modern, cross-platform user interface!

          ### 🚀 New Features

          - **🎨 Modern Flet UI**: Beautiful interface using Google's Flet framework
          - **🌐 Multi-language Support**: Dutch/English language switching
          - **🌙 Dark/Light Mode**: Toggle between themes
          - **📱 Responsive Design**: Adapts to different screen sizes
          - **⚡ Real-time Updates**: Instant UI language switching
          - **🔄 Enhanced Navigation**: Improved menu structure

          ### 🛠️ Technical Improvements

          - **Modern Framework**: Flet-based UI for future compatibility
          - **Translation System**: Comprehensive multi-language support
          - **Better Performance**: Improved state management
          - **Cross-platform**: Consistent experience across OS platforms
          - **Automated CI/CD**: GitHub Actions build pipeline

          ### 📋 Core Features

          - **Portfolio Management**: Add, edit, and organize portfolio items
          - **Feedback System**: Track feedback per learning outcome
          - **Document Generation**: Export to PDF and Markdown
          - **Learning Outcomes**: Detailed information and examples
          - **Student Data**: Easy configuration management

          ### 📦 Downloads

          Choose your platform:
          - **Windows**: `PortfolioManager-windows.exe`
          - **macOS**: `PortfolioManager-darwin`
          - **Linux**: `PortfolioManager-linux`

          ### 🔧 Installation

          1. Download the executable for your platform
          2. Run the executable (no installation required)
          3. Configure your student information
          4. Start managing your portfolio!

          ### 💻 Development Notes

          - Primary entry: `main_flet.py`
          - Legacy version: `main.py` (deprecated)
          - Requirements: See `requirements.txt`

          ---
          
          **🔗 Repository**: https://github.com/RickMageddon/PijlDocumentProgram
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        token: ${{ secrets.GITHUB_TOKEN }}
